applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-list',
    ),
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entradadetalle',
    ),
] 

applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'plantilla/', 
        views.TestPlantilla.as_view(),
        name='plantilla',
    ),  
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ),
    path(
        'index/', 
        views.HomePageView.as_view(),
        name='index',
    ),
    path(
        'subscriber/', 
        views.SuscriberCreateView.as_view(),
        name='subscriber',
    ),
    path(
        'contacto/', 
        views.ContactCreateView.as_view(),
        name='contacto',
    )
] 

blog/urls.py
"""
Proyecto Curso Django
"""
from unicodedata import name
from django.conf import  settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), #URL de ckeditor
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Objeto site map que general XML
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas':EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap,
        {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/home/models.py
from django.db import models
from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    """Modelo de pagina principal"""

    title = models.CharField(
        'Nombre',
        max_length=30
    )
    description = models.TextField()
    about_title = models.CharField(
        'Titulo Nosotros',
        max_length=50
    )
    about_text = models.TextField()
    contact_email = models.EmailField(
        'email de contacto',
        blank=True,
        null=True
    )
    phone = models.CharField(
        'Telefono de contacto',
        max_length=20
    )

    class Meta:
        verbose_name = 'Pagina Principal'
        verbose_name_plural = 'Pagina Principal'

    def __str__(self):
        return self.title

class Subscribers(TimeStampedModel):
    """Modelo de subscriptores"""

    email = models.EmailField()

    class Meta:
        verbose_name = 'Subscriptor'
        verbose_name_plural = 'Subscriptores'

    def __str__(self):
        return self.email

class Contact(TimeStampedModel):
    """Modelo de mensajes de formulario de contacto"""

    full_name = models.CharField(
        "Nombres", 
        max_length=50
    )
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Mensajes'

    def __str__(self):
        return self.full_name
            

applications/home/forms.py
from django import forms
from .models import Contact, Subscribers

class SuscriberForm(forms.ModelForm):
    """Formulario para el registro de subscribirse"""

    class Meta:
        model = Subscribers
        fields = (
            'email',
        )
        widgets = {
            'email':forms.EmailInput(
                attrs={
                    'placeholder':"Ingresa tu correo...",
                }
            ),
        }

class ContactForm(forms.ModelForm):
    """Formulario de contacto"""
    class Meta:
        model = Contact
        fields = ('__all__')

applications/home/views.py
import datetime
#
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from applications.entrada.models import Entry
from .models import Home
from .forms import SuscriberForm, ContactForm

from django.views.generic import (
    TemplateView,
    CreateView
)

class TestPlantilla(TemplateView):
    template_name = "plantillas/register.html"

class HomePageView(TemplateView):
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView,self).get_context_data(**kwargs)
        #Cargar el home
        context["home"] = Home.objects.latest("created")
        #Contexto de portada
        context["portada"] = Entry.objects.entrada_en_portada()
        #Contexto para articulos en home
        context["entradas_home"] = Entry.objects.entradas_en__home()
        #Contexto para entradas recientes
        context["entradas_recientes"] = Entry.objects.entradas_recientes()
        #Envio de formulario de suscripcion
        context["form"] = SuscriberForm
        return context

class SuscriberCreateView(CreateView):
    form_class = SuscriberForm
    success_url = '/'

class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '/'

templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/home/index.html
<!-- head para PC -->
{% extends "home/base_home.html" %}
{% load  static %}

{% block title %}
{{home.title}}
{% endblock title %}

{% block description %}
<meta name="description" content="{{home.description}}" />
{% endblock description %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <img src="{{portada.image.url}}">
                <div class="card-section">
                  <h4><a href="{% url 'entrada_app:entradadetalle' portada.slug %}">{{portada.title}}</a></h4>
                  <p>{{portada.resume | truncatechars:120}}</p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->

        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">
            {% for entrada in entradas_home %}
            <div class="cell small-12 large-6">
                <div class="card" style="width: 100%;">
                    <img src="{{entrada.image.url}}" style="height:120px;">
                    <div class="card-section">
                      <h5><a href="{% url 'entrada_app:entradadetalle' entrada.slug %}"> {{entrada.title | truncatechars:40}}</a></h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-10 callout secondary">
            <h5>{{home.about_title}}</h5>
            <p>
                {{home.about_text}}
            </p>

            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <form class="grid-x grid-margin-x" method="POST" action="{% url 'home_app:subscriber' %}">
                    {% csrf_token %}
                    <div class="cell small-12">
                        {{form.email}}
                    </div>
                    <div class="cell small-12">
                        <button type="submit" class="success button">Suscribirme</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center">
        <h3 class="cell">Articulos Recientes:</h3>
        {% for entrada in entradas_recientes %}
        <div class="cell small-6 large-4">
            <div class="card" style="width: 100%;">
                <img src="{{entrada.image.url}}" style="height:180px;">
                <div class="card-section">
                    <h4><a href="{% url 'entrada_app:entradadetalle' entrada.slug %}">{{entrada.title}}</a></h4>
                    <p>{{entrada.resume | truncatechars:120}}</p>
                </div>
            </div>
        </div> 
        {% endfor %}
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}