applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-list',
    ),
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entradadetalle',
    ),
] 

applications/favoritos/urls.py
#
from django.urls import path

from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageListView.as_view(),
        name='perfil',
    ),
    path(
        'add-entry/<pk>', 
        views.AddFavoriteView.as_view(),
        name='add-favoritos',
    ),
    path(
        'delete-favorites/<pk>', 
        views.RemoveFavoriteView.as_view(),
        name='delete-favoritos',
    )
]

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from unicodedata import name
from django.conf import  settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), #URL de ckeditor
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Objeto site map que general XML
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas':EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap,
        {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/favoritos/models.py
from enum import unique
from django.db import models
from django.conf import settings
from applications.users.models import User

from model_utils.models import TimeStampedModel
from applications.entrada.models import Entry
from .managers import FavoritesManager

class Favorites(TimeStampedModel):
    """Modelo para favoritos"""

    user = models.ForeignKey(
        User,
        related_name='user_favorites',
        on_delete=models.CASCADE
    )
    entry = models.ForeignKey(
        Entry,
        related_name='entry_favorites',
        on_delete=models.CASCADE
    )

    objects = FavoritesManager()

    class Meta:
        unique_together = ('user','entry') #Que no sean iguales
        verbose_name = 'Entrada Favorita'
        verbose_name_plural = "Entradas Favoritas"

    def __str__(self):
        return self.entry.title

applications/favoritos/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, View, DeleteView
from applications.entrada.models import Entry
from .models import Favorites

class UserPageListView(LoginRequiredMixin,ListView):
    template_name = "favoritos/perfil.html"
    context_object_name = 'entradas_user'
    login_url = reverse_lazy('users_app:user-login')

    def get_queryset(self):
        return Favorites.objects.entradas_user(self.request.user)

class AddFavoriteView(LoginRequiredMixin,View):
    login_url = reverse_lazy('users_app:user-login')

    def post(self,request,*args,**kwargs):

        #Recuperar usuario y id de entrada actual
        usuario = self.request.user
        entrada = Entry.objects.get(id=self.kwargs['pk'])

        #Registrar a favoritos
        Favorites.objects.create(
            user=usuario,
            entry = entrada
        )

        return HttpResponseRedirect(
            reverse(
                'favoritos_app:perfil'
            )
        )

class RemoveFavoriteView(DeleteView):
    model = Favorites
    success_url="/perfil"

templates/favoritos/base_favoritos.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/favoritos/perfil.html
<!-- head para PC -->
{% extends "favoritos/base_favoritos.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout">
                <h5>{{user.full_name}}</h5>
                <p>{{user.email}} {{user.ocupation}} - {{user.date_birth}}</p>
                <a href="#">Editar Datos</a>
                <p>
                    <a href="{% url 'users_app:user-logout' %}" class="clear button secondary">Salir</a>
                </p>
            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->


        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">
            {% for entrada  in entradas_user %}
            <div class="cell small-12">
                <div class="card-favoritos">
                    <img class="card-favoritos-img" src="{{entrada.entry.image.url}}">
                    <div class="card-favoritos-body">
                        <h3 class="card-favoritos-body-titulo">{{entrada.entry.title}}</h3>
                        <p class="card-favoritos-body-text">{{entrada.entry.resume}}</p>
                        <form class="card-favoritos-body-actions" action="{% url 'favoritos_app:delete-favoritos' entrada.id %}" method="POST">{% csrf_token %}
                            <a class="button warning" href="{% url 'entrada_app:entradadetalle' entrada.entry.slug %}">Ver</a>
                            <button type="submit" class="button alert" href="#">Eliminar</button>
                        </form>
                    </div>
                </div>
            </div>
            {%empty%}
            <h3 style="color:red;">No hay articulos favoritos :)</h3>
            {% endfor %}
        </div>
        <!-- FIN bloque de articulos favoritos de usuario -->
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}