applications/entrada/urls.py
#
from django.urls import path
from . import views

app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas/', 
        views.EntryListView.as_view(),
        name='entry-list',
    ),
    path(
        'entrada/<slug>/', 
        views.EntryDetailView.as_view(),
        name='entradadetalle',
    ),
] 

applications/favoritos/urls.py
#
from django.urls import path

from . import views

app_name = "favoritos_app"

urlpatterns = [
    path(
        'perfil/', 
        views.UserPageListView.as_view(),
        name='perfil',
    ),
    path(
        'add-entry/<pk>', 
        views.AddFavoriteView.as_view(),
        name='add-favoritos',
    ),
    path(
        'delete-favorites/<pk>', 
        views.RemoveFavoriteView.as_view(),
        name='delete-favoritos',
    )
]

applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        'plantilla/', 
        views.TestPlantilla.as_view(),
        name='plantilla',
    ),  
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ),
    path(
        'index/', 
        views.HomePageView.as_view(),
        name='index',
    ),
    path(
        'subscriber/', 
        views.SuscriberCreateView.as_view(),
        name='subscriber',
    ),
    path(
        'contacto/', 
        views.ContactCreateView.as_view(),
        name='contacto',
    )
] 

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from unicodedata import name
from django.conf import  settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), #URL de ckeditor
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Objeto site map que general XML
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas':EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap,
        {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Formulario de Contacto:</h3>
        <form class="cell small-12 large-7" method="POST" action="{% url 'home_app:contacto' %}"> {% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>Nombres
                    <input type="text" placeholder="nombres..." name="full_name" id="full_name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Correo
                    <input type="text" placeholder="Correo ..." name="email" id="email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Mensaje
                        <textarea placeholder="Mensaje" name="message" id="id_message"></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="success button">Enviar</button>
                </div>
            </div>
        </form>
        <p class="cell large-8">Otras formas de contacto</p>
        <p class="cell large-8">
          <span class="label warning">{{correo}}</span>
          <span class="label warning">{{phone}}</span>
        </p>
    </div>
</div>

templates/includes/header.html
<header>
    <div class="grid-x grid-margin-x header">
        <div class="cell small-12 medium-4 large-3">
            <a href="/" style="font-size: 20px; color: #0277bd;">
                ED Blog
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="{% url 'home_app:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'entrada_app:entry-list' %}">Blog</a>
                </li>
                <li>
                    {% if not user.is_anonymous %}
                    <a  href="{% url 'favoritos_app:perfil' %}" class="warning button">Ir a perfil</a>
                    {% else %}
                    <a  href="{% url 'users_app:user-login' %}" class="success button">Acceder</a>
                    {% endif %}
                </li>
                
            </ul>
        </div>
    </div>
</header>