applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/urls.py
"""
Proyecto Curso Django
"""
from unicodedata import name
from django.conf import  settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

from django.contrib.sitemaps.views import sitemap
from applications.home.sitemap import EntrySitemap, Sitemap

urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), #URL de ckeditor
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Objeto site map que general XML
sitemaps = {
    'site':Sitemap(
        [
            'home_app:index'
        ]
    ),
    'entradas':EntrySitemap
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml', 
        sitemap,
        {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]

urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
#
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    email = models.EmailField(unique=True)
    full_name = models.CharField('Nombres', max_length=100)
    ocupation = models.CharField(
        'Ocupacion',
        max_length=30, 
        blank=True
    )
    genero = models.CharField(
        max_length=1, 
        choices=GENDER_CHOICES, 
        blank=True
    )
    date_birth = models.DateField(
        'Fecha de nacimiento', 
        blank=True,
        null=True
    )
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def get_short_name(self):
        return self.email
    
    def get_full_name(self):
        return self.full_name

applications/users/forms.py
from django import forms
from django.contrib.auth import authenticate
#
from .models import User

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repetir Contraseña'
            }
        )
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            'email',
            'full_name',
            'ocupation',
            'genero',
            'date_birth',
        )

        widgets = {
            'email':forms.EmailInput(
                attrs={
                    'placeholder':'Correo electronico...'
                }
            ),
            'full_name':forms.TextInput(
                attrs={
                    'placeholder':'Nombre(s)...'
                }
            ),
            'ocupation':forms.TextInput(
                attrs={
                    'placeholder':'Ocupacion...'
                }
            ),
            'date_birth':forms.DateInput(
                attrs={
                    'type':'date',
                }
            ),
        }
    
    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    email = forms.CharField(
        label='E-mail',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Correo Electronico',
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')
        
        return self.cleaned_data


class UpdatePasswordForm(forms.Form):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Actual'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Nueva'
            }
        )
    )

applications/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.views.generic import (
    View,
    CreateView
)

from django.views.generic.edit import (
    FormView
)

from .forms import (
    UserRegisterForm, 
    LoginForm,
    UpdatePasswordForm,
)
#
from .models import User
# 


class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        #
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            full_name = form.cleaned_data['full_name'],
            ocupation=form.cleaned_data['ocupation'],
            genero=form.cleaned_data['genero'],
            date_birth=form.cleaned_data['date_birth'],
        )
        # enviar el codigo al email del user
        return super(UserRegisterView, self).form_valid(form)



class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('favoritos_app:perfil')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)

templates/users/base_users.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/users/login.html
<!-- head para PC -->
{% extends "users/base_users.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell medium-6 large-4" style="margin-top: 2em;">
            <div class="card" style="width: 100%;">
                <div class="card-divider">
                  <h4>Acceso de usuario</h4>
                </div>
                <div class="card-section">
                    <form class="grid-x grid-margin-x" method="POST" enctype="multipar/form-data">{% csrf_token %}
                        <div class="cell medium-12">
                            <label>Email:
                            {{form.email}}
                            </label>
                        </div>
                        <div class="cell medium-12">
                            <label>Contraseña:
                                {{form.password}}
                            </label>
                        </div>
                        <button type="submit" class="cell hollow button primary">Acceder</button>
                        <a class="cell hollow button alert" href="{% url 'users_app:user-register'%}">Registrar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/users/register.html
<!-- head para PC -->
{% extends "users/base_users.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell medium-10 large-6" style="margin-top: 2em;">
            <div class="card" style="width: 100%;">
                <div class="card-divider">
                  <h4>Ingrese sus datos</h4>
                </div>
                <div class="card-section">
                    <form class="grid-x grid-margin-x" action="" method="POST" enctype="multipar/form-data">{% csrf_token %}
                                                
                        <div class="cell large-12">
                            <label>Email:
                            {{form.email}}
                            </label>
                        </div>
                        <div class="cell large-6">
                            <label>Nombres:
                            {{form.full_name}}
                            </label>
                        </div>
                        <div class="cell medium-6">
                            <label>Ocupacion:
                                {{form.ocupation}}
                            </label>
                        </div>
                        <div class="cell medium-6">
                            <label>Genero:
                                {{form.genero}}
                            </label>
                        </div>
                        <div class="cell medium-6">
                            <label>Fecha Nacimiento:
                                {{form.date_birth}}
                            </label>
                        </div>
                        <div class="cell medium-12">
                            <label>Contraseña:
                                {{form.password1}}
                            </label>
                        </div>
                        <div class="cell medium-12">
                            <label>Repetir Contraseña:
                                {{form.password2}}
                            </label>
                            {% for e in form.password2.errors %}
                            <p style="color:red;">{{e}}</p>
                            {% endfor %}
                        </div>
                        <button type="submit" class="cell hollow button primary">Registrar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}